### ISSUE TITLE
Out of Class Work : Complete goals, hills, definitions & sub-hills Mural 

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2023_Team3#10]
Decomposing a goal into three hills (objectives) using written language can be challenging as every word has to carry its own weight and add more and more clarity. Remember that the goal statement beneficiary may be impacted by other stakeholders which can be addressed in individual hill statements.

One hill will be chosen by the team to define what every key word means so the team can get aligned on the meaning and implications of the hill statement. 

Sub-hills will use the POEMS framework to get into all the details of the hill statement and to clarify the goal statement. Team questions and assumptions should be used to address key issues and to add clarity to gaps in thinking of the chosen project and inform sub-hill details.

This is a critical group exercise and cannot be done asynchronously. Be prepared to invest two to three hours of time, in one or two synchronous sessions.

Team 1 : https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1698260725622/cb9d0a38694a4877cc5ca74f4091838a55fcacd4?sender=u8174af0a23de37cd1e842670

Team 2 : https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1698260752590/39072f938b55e0f76a7279d5564867dc205796e8?sender=u8174af0a23de37cd1e842670

Team 3 : https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1698260769378/e1f16d63c716df4c9891fe9e70fc13b0d79e0f5c?sender=u8174af0a23de37cd1e842670

- [ ] Keval Mayur Parekh 
- [ ] Daniela Vélez 
- [ ] Jiafeng Zhu

@kepa5, @dvelezm3, @jzhu68

**Comment by akallish** [comment]
@kepa5, @dvelezm3, @jzhu68 Hello! I reviewed some of your Mural Hills sandbox today. Overall, a good start. Many of my comments were about sharpening the clarity of specific statements and definitions. Rewriting is critical to get rid of words or statements that are not clear and achieving crystal clarity. Agile demands this in order to do the work right. Keep iterating and refining.

**Comment by akallish** [comment]
@kepa5, @dvelezm3, @jzhu68 I reviewed your Hills sandbox this morning. Good progress is being made. I left additional comments and suggestions in a few sub-hill statements. Remember sub-hills need to address the what or wow statement and describe specific features and functions that your proposed platform will provide stakeholders. Please sharpen your sub-hills as clear "how" statements of the value delivered.

**Comment by akallish** [comment]
@jzhu68 I see this issue is in QA. Has the team refined their sandbox after Wednesday's class?

**Comment by jzhu68** [comment]
@akallish Yes we will revisit and refine our subhills when writing stories in today's meeting.

**Comment by akallish** [comment]
@jzhu68 thanks for the update. If the team wants me to review specific changes "@" me
