### ISSUE TITLE
Providing feedback to students

### ISSUE THREAD

**Issue by kepa5** [IITIDIDX597/F2023_Team3#28]
### Goal Statement: 
For: Design Students in Chicago
Who: are looking for opportunities to grow, network, and upskill to start their careers and make an impact
Your: Gigs for Good
Is a: transparent, curated and accessible digital platform
That: students can engage to seek relevant work or volunteer-ships, grow their professional network, meet people and acquire new skills.

### Hill Statement:
Who: Design students in Chicago
What: can volunteer for nonprofits in the form of part-time or full-time gigs, can participate in workshop classes and events organized in the museum
Wow: grow a professional network easily, get to meet people with similar interests without any barriers of digital networking and acquire new skills without any costs

### Sub-hill statement:
When volunteering work is complete, a non-profit must provide feedback on the Gigs for Good platform by acknowledging the student's quality of outcome.
- **Forms of review:** rates, tags, short reviews or showcasing outcome
- **Content of review:** design skills, communication abilities, time management 

### Story statement:
As a non-profit
I want: to provide constructive feedback to a volunteer student
So that: I their work for my organization improves

**Comment by akallish** [comment]
@kepa5 @jzhu68 @dvelezm3 Thanks for posting this draft story. I am not sure what sub-hill statement this traces to, but there are some challenges with your statement :

- As a non-profit
Comment : This is clear
- I want to provide feedback to the volunteer student
Comment : "I want to provide constructive feedback to a volunteer student"
- So I can acknowledge their effort and achievement
Comment : "So their work for my organization improves"?
