### ISSUE TITLE
Out of Class Work : Read Online Articles

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2023_Team3#7]
https://www.ibm.com/design/thinking/page/toolkit/activity/writing-hills

https://www.ibm.com/garage/method/practices/think/practice_hills/

- [ ] Keval Mayur Parekh 
- [ ] Daniela Vélez 
- [ ] Jiafeng Zhu

@kepa5, @dvelezm3, @jzhu68

**Comment by akallish** [comment]
What stood out in terms of key points from these online articles that resonated with you.

**Comment by kepa5** [comment]
- **Most valuable outcomes** for the user and **Most important differentiators** for organization
- Hills **don't need to be perfect** and they evolve over time (@akallish but I wonder how long that goes and is there a need to put a sort of time limit to finalising Hills?)

**Comment by akallish** [comment]
@kepa5 thanks for your comment and question. A hill statement can be completed in one sprint or several sprints. Sometimes a hill statement may be modified as the details and constraints become clearer.

As a product grows new goals and hill are drafted on the new capabilities that are added.

**Comment by akallish** [comment]
@kepa5, @dvelezm3, @jzhu68 This issue should be closed
